### ISSUE TITLE
【質問】改訂版P176 REST APIの結合テストにて実行エラー

### ISSUE THREAD

**Issue by hidetarou2013** [making/hajiboot-samples#60]
お世話になります。

早速ですが、改訂版P176 REST APIの結合テストにて、
テキストどうりの

```
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
        properties = {"spring.datasource.url:jdbc:h2:mem:customers;DB_CLOSE_ON_EXIT=FALSE"})
```

で実行した場合、p178に記載の説明によるとテスト時にインメモリのデータベースを使えるとあるのですが、
こちらでは、以下のエラーが出ます。

```
java.sql.SQLException: Driver:net.sf.log4jdbc.DriverSpy@5d8ab698 returned null for URL:jdbc:h2:mem:customers;DB_CLOSE_ON_EXIT=FALSE
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:329) ~[tomcat-jdbc-8.5.4.jar:na]
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:203) ~[tomcat-jdbc-8.5.4.jar:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:716) [tomcat-jdbc-8.5.4.jar:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:648) [tomcat-jdbc-8.5.4.jar:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:468) [tomcat-jdbc-8.5.4.jar:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:143) [tomcat-jdbc-8.5.4.jar:na]
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:118) [tomcat-jdbc-8.5.4.jar:na]
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:107) [tomcat-jdbc-8.5.4.jar:na]

```

ちなみに、ファイルベースの設定にすると、テスト実施に成功します。
原因わかりますでしょうか？

よろしくお願いします。

以下の設定だとうまくいくのですが。。。

```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
properties = {"spring.datasource.url:jdbc:log4jdbc:h2:file:./target/db/customer;DB_CLOSE_ON_EXIT=FALSE"})

```

**Comment by hidetarou2013** [comment]
あ、自己解決しました。

```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
        properties = {"spring.datasource.url:jdbc:log4jdbc:h2:mem:customers;DB_CLOSE_ON_EXIT=FALSE"})
```

ですね。

テキストの記述の修正以下にすればうまくいくようです。

変更前
spring.datasource.url:jdbc:h2:mem:customers;DB_CLOSE_ON_EXIT=FALSE

変更後
spring.datasource.url:jdbc:log4jdbc:h2:mem:customers;DB_CLOSE_ON_EXIT=FALSE


よろしくお願いします。
