### ISSUE TITLE
Cannot load driver class: net.sf.log4jdbc.DriverSpyのエラー

### ISSUE THREAD

**Issue by gachakra** [making/hajiboot-samples#64]
お世話になっております。
はじめてのSpring Boot [改訂版] 第１版第2刷を読んで勉強しております。
わかりやすい内容でとてもためになっております。

P.56の[2.2.3]でエラーが解消できず先に進めなくなってしまったので
こちらに投稿いたします。

下記２つを設定し、runしたところ標題のエラーが出てしまいます。

**・log4jdbcをpon.xmlに以下を追記**
```
		<dependency>
			<groupId>org.lazyluke</groupId>
			<artifactId>log4jdbc-remix</artifactId>
			<version>0.2.7</version>
		</dependency>
```

**・application.propertiesに以下を記載**
```
spring.datasource.driver-class-name=net.sf.log4jdbc.DriverSpy
spring.datasource.url=jdbc:log4jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
logging.level.jdbc=OFF
logging.level.jdbc.sqltiming=DEBUG
```

尚、log4jdbcを使用する直前の[2.2.2]までは正常に動作しており、
log4jdbc-remix-0.2.7.jarもローカルの以下パスにダウンロードされておりました。
`~/.m2/repository/org/lazyluke/log4jdbc-remix/0.2.7/log4jdbc-remix-0.2.7.jar
`

エラーメッセージ：
```
Caused by: java.lang.IllegalStateException: Cannot load driver class: net.sf.log4jdbc.DriverSpy
	at org.springframework.util.Assert.state(Assert.java:392) ~[spring-core-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.determineDriverClassName(DataSourceProperties.java:203) ~[spring-boot-autoconfigure-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration.createDataSource(DataSourceConfiguration.java:42) ~[spring-boot-autoconfigure-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Tomcat.dataSource(DataSourceConfiguration.java:55) ~[spring-boot-autoconfigure-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	... 56 common frames omitted
```

なにかおわかりになりますでしょうか。
よろしくお願いいたします。

**Comment by making** [comment]
このレポジトリのコードを使っても同じ事象になりますか？

**Comment by gachakra** [comment]
はい。
2.2.3_hajiboot-jdbc
でmaven projectととして実行しても
同じエラーが発生しました。

**Comment by making** [comment]
自分の環境では動きますね。jarが壊れているかもしれません。

`~/.m2/repository/org/lazyluke/log4jdbc-remix/0.2.7/log4jdbc-remix-0.2.7.jar`を削除してもう一回試してもらえます？

```
$ ./mvnw clean spring-boot:run

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building hajiboot-jdbc 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ hajiboot-jdbc ---
[INFO] Deleting /Users/makit/git/hajiboot-samples/chapter02/2.2.3_hajiboot-jdbc/target
[INFO] 
[INFO] >>> spring-boot-maven-plugin:1.4.0.RELEASE:run (default-cli) > test-compile @ hajiboot-jdbc >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hajiboot-jdbc ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ hajiboot-jdbc ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/makit/git/hajiboot-samples/chapter02/2.2.3_hajiboot-jdbc/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ hajiboot-jdbc ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/makit/git/hajiboot-samples/chapter02/2.2.3_hajiboot-jdbc/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ hajiboot-jdbc ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/makit/git/hajiboot-samples/chapter02/2.2.3_hajiboot-jdbc/target/test-classes
[INFO] 
[INFO] <<< spring-boot-maven-plugin:1.4.0.RELEASE:run (default-cli) < test-compile @ hajiboot-jdbc <<<
[INFO] 
[INFO] --- spring-boot-maven-plugin:1.4.0.RELEASE:run (default-cli) @ hajiboot-jdbc ---

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.4.0.RELEASE)

2017-06-28 15:55:53.860  INFO 39425 --- [           main] com.example.HajibootJdbcApplication      : Starting HajibootJdbcApplication on jpxxmakitm1.corp.emc.com with PID 39425 (/Users/makit/git/hajiboot-samples/chapter02/2.2.3_hajiboot-jdbc/target/classes started by makit in /Users/makit/git/hajiboot-samples/chapter02/2.2.3_hajiboot-jdbc)
2017-06-28 15:55:53.864  INFO 39425 --- [           main] com.example.HajibootJdbcApplication      : No active profile set, falling back to default profiles: default
2017-06-28 15:55:53.934  INFO 39425 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@637b4ca4: startup date [Wed Jun 28 15:55:53 JST 2017]; root of context hierarchy
2017-06-28 15:55:55.035  INFO 39425 --- [           main] o.s.jdbc.datasource.init.ScriptUtils     : Executing SQL script from URL [file:/Users/makit/git/hajiboot-samples/chapter02/2.2.3_hajiboot-jdbc/target/classes/schema.sql]
2017-06-28 15:55:55.051 DEBUG 39425 --- [           main] jdbc.sqltiming                           :  org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:473)
10. CREATE table customers(id int primary key auto_increment, first_name varchar(30), last_name 
varchar(30))  {executed in 11 msec}
2017-06-28 15:55:55.052  INFO 39425 --- [           main] o.s.jdbc.datasource.init.ScriptUtils     : Executed SQL script from URL [file:/Users/makit/git/hajiboot-samples/chapter02/2.2.3_hajiboot-jdbc/target/classes/schema.sql] in 17 ms.
2017-06-28 15:55:55.054  INFO 39425 --- [           main] o.s.jdbc.datasource.init.ScriptUtils     : Executing SQL script from URL [file:/Users/makit/git/hajiboot-samples/chapter02/2.2.3_hajiboot-jdbc/target/classes/data.sql]
2017-06-28 15:55:55.057 DEBUG 39425 --- [           main] jdbc.sqltiming                           :  org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:473)
10. INSERT INTO customers(first_name, last_name) VALUES('Nobita', 'Nobi')  {executed in 2 msec}
2017-06-28 15:55:55.058 DEBUG 39425 --- [           main] jdbc.sqltiming                           :  org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:473)
10. INSERT INTO customers(first_name, last_name) VALUES('Takeshi', 'Goda')  {executed in 1 msec}
2017-06-28 15:55:55.058 DEBUG 39425 --- [           main] jdbc.sqltiming                           :  org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:473)
10. INSERT INTO customers(first_name, last_name) VALUES('Suneo', 'Honekawa')  {executed in 0 msec}
2017-06-28 15:55:55.059 DEBUG 39425 --- [           main] jdbc.sqltiming                           :  org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:473)
10. INSERT INTO customers(first_name, last_name) VALUES('Shizuka', 'Minamoto')  {executed in 0 msec}
2017-06-28 15:55:55.059  INFO 39425 --- [           main] o.s.jdbc.datasource.init.ScriptUtils     : Executed SQL script from URL [file:/Users/makit/git/hajiboot-samples/chapter02/2.2.3_hajiboot-jdbc/target/classes/data.sql] in 5 ms.
2017-06-28 15:55:55.274  INFO 39425 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2017-06-28 15:55:55.307 DEBUG 39425 --- [           main] jdbc.sqltiming                           :  org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:692)
10. SELECT id, first_name, last_name FROM customers WHERE id = 1  {executed in 6 msec}
result = Customer(id=1, firstName=Nobita, lastName=Nobi)
2017-06-28 15:55:55.321  INFO 39425 --- [           main] com.example.HajibootJdbcApplication      : Started HajibootJdbcApplication in 6.573 seconds (JVM running for 11.369)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.802 s
[INFO] Finished at: 2017-06-28T15:55:55+09:00
[INFO] Final Memory: 32M/392M
[INFO] ------------------------------------------------------------------------
2017-06-28 15:55:55.504  INFO 39425 --- [       Thread-2] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@637b4ca4: startup date [Wed Jun 28 15:55:53 JST 2017]; root of context hierarchy
2017-06-28 15:55:55.505  INFO 39425 --- [       Thread-2] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
```

**Comment by gachakra** [comment]
~/.m2/repository/org/lazyluke/
を削除して実行したらエラー解消されました。

お手数お掛けいたしました。
ありがとうございました！
